### PR TITLE
improved Win32 Makefiles

### PR DESCRIPTION
**Pull request by kajott**
- unified 32-bit and 64-bit Windows Makefiles
- SDL2 headers and libs are downloaded automatically as part of the build process
- various other fixes and additions related to Win32 builds

The end result is that you can now simply use a stock Ubuntu, `apt install mingw-w64`, and `make -f Makefile.win32` "just works". It doesn't even feel like cross-compiling when run in WSL ;)

### CODE REVIEW

**Comment by sulix** [comment]
This worked perfectly for me when I tried it, thanks!

A few notes:
1. This now links statically by default. I can see the appeal, but it'd be nice to still have a way to link dynamically.
1. Could we use the sdl2-config that's included with the mingw version of SDL2 we download? This would get rid of the need to have things like the huge list of statically linked libraries (we can just use --static-libs if we want to link statically), and also the need for the WinMain function at all (as SDL will provide a  -Dmain=SDL_main). I found that this worked with:
```SDL_CONFIG=$(SDL_DIR)/$(TOOLSET)/bin/sdl2-config --prefix=$(SDL_DIR)/$(TOOLSET)```
1. If we don't do that, can we run ck_main.c through clang-format, which will fix a few minor style issues (none of which really matter, but my goal is to one day have everything match the style guide). Otherwise, if we can get rid of the WinMain bit all together, it doesn't matter.
1. We need to add -DWITH_SDL to the CFLAGS somehow in the using-sdlconfig path, as otherwise it won't build due to "undefined reference to `VL_SDL2GL_SetIcon'"

What do you think of those ideas? If you'd rather I make those changes for you, let me know.

A final thought:
One thing I want to eventually do is to have a single build system across all platforms (either extending the main Makefile — which already mostly supports DOS as well, or switching to something like CMake, which would be able to generate things like Visual Studio projects as well). If you want to have a go at integrating changes like this into the main Makefile (with PLATFORM=windows), feel free — otherwise, I'll try to include something like the auto-download of SDL2 when I get around to this.

**Comment by kajott** [comment]
> - This now links statically [...] but it'd be nice to still have a way to link dynamically.
> - Could we use the sdl2-config that's included with the mingw version of SDL2 we download?
> - We need to add -DWITH_SDL to the CFLAGS somehow in the using-sdlconfig path

Good ideas, I'll give it a shot tonight.

> If you want to have a go at integrating changes like this into the main Makefile (with PLATFORM=windows), feel free

I'll see what I can do.

> switching to something like CMake

I had that idea too, but as I wanted to get quick results, I settled for the good old Makefiles first :)

> which would be able to generate things like Visual Studio projects as well

Yes, but that wouldn't be very useful unless we get rid of the GCC-isms in the code (like `__attribute__((__packed__))`).

**Comment by sulix** [comment]
> > * This now links statically [...] but it'd be nice to still have a way to link dynamically.
> > * Could we use the sdl2-config that's included with the mingw version of SDL2 we download?
> > * We need to add -DWITH_SDL to the CFLAGS somehow in the using-sdlconfig path
> 
> Good ideas, I'll give it a shot tonight.

Thanks! It'd definitely be nice to get rid of the big list of Windows DLLs in STATIC_LIBS.

> > If you want to have a go at integrating changes like this into the main Makefile (with PLATFORM=windows), feel free
> 
> I'll see what I can do.

Thanks — feel free to do this in a separate PR if you'd prefer: I am happy to take this change regardless.

> > switching to something like CMake
> 
> I had that idea too, but as I wanted to get quick results, I settled for the good old Makefiles first :)
> 
> > which would be able to generate things like Visual Studio projects as well
> 
> Yes, but that wouldn't be very useful unless we get rid of the GCC-isms in the code (like `__attribute__((__packed__))`).

True — it's something of a longer-term goal. (We eventually did this with the — now defunct — Steam version of Keen Dreams, as Steam's ABI and/or overlay code had problems with mingw32.)


Thanks very much!

**Comment by kajott** [comment]
OK, we're now using `sdl2-config` no matter what, and it makes life much easier indeed. My custom `WinMain` implementation has been removed again. Also, there's an option to dynamically link against SDL2 (`STATIC=0`).

I did *not* merge the Windows and DOS/Unix Makefiles yet, simply because the naming of this branch and PR would be quite misleading then :) I will cook up a unified Makefile and issue a new PR once this one has been merged though.

**Comment by sulix** [comment]
I tried out the various combinations here, and it all works great. Thanks especially for making more of the variables settable from the make command-line!

**Pull request merged**
